---
# handlers file for ansible-role-nexus

- name: start nexus service
  become: yes
  service:
    name: nexus
    state: started

- name: stop nexus service
  become: yes
  service:
    name: nexus
    state: stopped

- name: restart nexus service
  become: yes
  service:
    name: nexus
    state: restarted

- name: reload nexus service
  become: yes
  service:
    name: nexus
    state: reloaded

- name: reload firewalld
  become: yes
  service:
    name: firewalld
    state: reloaded
