---
# handlers file for ansible-role-nexus

- name: Start nexus service
  become: yes
  service:
    name: nexus
    state: started

- name: Stop nexus service
  become: yes
  service:
    name: nexus
    state: stopped

- name: restart nexus service
  become: yes
  service:
    name: nexus
    state: restarted

- name: Reload nexus service
  become: yes
  service:
    name: nexus
    state: reloaded
